#solr 单节点配置
#url: http://localhost:8080/solr/collection1
solr-url: http://localhost:8080/solr

#solr cloud 配置
zks: 192.168.2.3:2181,192.168.2.4:2181,192.168.2.5:2181

#log
logging:
  level:
    root: info