// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student.proto

package com.study.myprotobuf.dto;

public final class StudentProto {
  private StudentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface studentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:student)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 学生名称
     * </pre>
     *
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <pre>
     * 学生名称
     * </pre>
     *
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <pre>
     * 学生名称
     * </pre>
     *
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     * 学生年龄
     * </pre>
     *
     * <code>required int32 age = 2;</code>
     */
    boolean hasAge();
    /**
     * <pre>
     * 学生年龄
     * </pre>
     *
     * <code>required int32 age = 2;</code>
     */
    int getAge();

    /**
     * <pre>
     * 学生所修课程，可能是多门，是一组数组
     * </pre>
     *
     * <code>repeated .course course = 3;</code>
     */
    java.util.List<com.study.myprotobuf.dto.CourseProto.course> 
        getCourseList();
    /**
     * <pre>
     * 学生所修课程，可能是多门，是一组数组
     * </pre>
     *
     * <code>repeated .course course = 3;</code>
     */
    com.study.myprotobuf.dto.CourseProto.course getCourse(int index);
    /**
     * <pre>
     * 学生所修课程，可能是多门，是一组数组
     * </pre>
     *
     * <code>repeated .course course = 3;</code>
     */
    int getCourseCount();
    /**
     * <pre>
     * 学生所修课程，可能是多门，是一组数组
     * </pre>
     *
     * <code>repeated .course course = 3;</code>
     */
    java.util.List<? extends com.study.myprotobuf.dto.CourseProto.courseOrBuilder> 
        getCourseOrBuilderList();
    /**
     * <pre>
     * 学生所修课程，可能是多门，是一组数组
     * </pre>
     *
     * <code>repeated .course course = 3;</code>
     */
    com.study.myprotobuf.dto.CourseProto.courseOrBuilder getCourseOrBuilder(
        int index);
  }
  /**
   * <pre>
   * 定义学生模板
   * </pre>
   *
   * Protobuf type {@code student}
   */
  public  static final class student extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:student)
      studentOrBuilder {
    // Use student.newBuilder() to construct.
    private student(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private student() {
      name_ = "";
      age_ = 0;
      course_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private student(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              age_ = input.readInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                course_ = new java.util.ArrayList<com.study.myprotobuf.dto.CourseProto.course>();
                mutable_bitField0_ |= 0x00000004;
              }
              course_.add(
                  input.readMessage(com.study.myprotobuf.dto.CourseProto.course.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          course_ = java.util.Collections.unmodifiableList(course_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.study.myprotobuf.dto.StudentProto.internal_static_student_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.study.myprotobuf.dto.StudentProto.internal_static_student_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.study.myprotobuf.dto.StudentProto.student.class, com.study.myprotobuf.dto.StudentProto.student.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <pre>
     * 学生名称
     * </pre>
     *
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * 学生名称
     * </pre>
     *
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * 学生名称
     * </pre>
     *
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private int age_;
    /**
     * <pre>
     * 学生年龄
     * </pre>
     *
     * <code>required int32 age = 2;</code>
     */
    public boolean hasAge() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * 学生年龄
     * </pre>
     *
     * <code>required int32 age = 2;</code>
     */
    public int getAge() {
      return age_;
    }

    public static final int COURSE_FIELD_NUMBER = 3;
    private java.util.List<com.study.myprotobuf.dto.CourseProto.course> course_;
    /**
     * <pre>
     * 学生所修课程，可能是多门，是一组数组
     * </pre>
     *
     * <code>repeated .course course = 3;</code>
     */
    public java.util.List<com.study.myprotobuf.dto.CourseProto.course> getCourseList() {
      return course_;
    }
    /**
     * <pre>
     * 学生所修课程，可能是多门，是一组数组
     * </pre>
     *
     * <code>repeated .course course = 3;</code>
     */
    public java.util.List<? extends com.study.myprotobuf.dto.CourseProto.courseOrBuilder> 
        getCourseOrBuilderList() {
      return course_;
    }
    /**
     * <pre>
     * 学生所修课程，可能是多门，是一组数组
     * </pre>
     *
     * <code>repeated .course course = 3;</code>
     */
    public int getCourseCount() {
      return course_.size();
    }
    /**
     * <pre>
     * 学生所修课程，可能是多门，是一组数组
     * </pre>
     *
     * <code>repeated .course course = 3;</code>
     */
    public com.study.myprotobuf.dto.CourseProto.course getCourse(int index) {
      return course_.get(index);
    }
    /**
     * <pre>
     * 学生所修课程，可能是多门，是一组数组
     * </pre>
     *
     * <code>repeated .course course = 3;</code>
     */
    public com.study.myprotobuf.dto.CourseProto.courseOrBuilder getCourseOrBuilder(
        int index) {
      return course_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAge()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getCourseCount(); i++) {
        if (!getCourse(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, age_);
      }
      for (int i = 0; i < course_.size(); i++) {
        output.writeMessage(3, course_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, age_);
      }
      for (int i = 0; i < course_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, course_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.study.myprotobuf.dto.StudentProto.student)) {
        return super.equals(obj);
      }
      com.study.myprotobuf.dto.StudentProto.student other = (com.study.myprotobuf.dto.StudentProto.student) obj;

      boolean result = true;
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && (hasAge() == other.hasAge());
      if (hasAge()) {
        result = result && (getAge()
            == other.getAge());
      }
      result = result && getCourseList()
          .equals(other.getCourseList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasAge()) {
        hash = (37 * hash) + AGE_FIELD_NUMBER;
        hash = (53 * hash) + getAge();
      }
      if (getCourseCount() > 0) {
        hash = (37 * hash) + COURSE_FIELD_NUMBER;
        hash = (53 * hash) + getCourseList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.study.myprotobuf.dto.StudentProto.student parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.study.myprotobuf.dto.StudentProto.student parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.study.myprotobuf.dto.StudentProto.student parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.study.myprotobuf.dto.StudentProto.student parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.study.myprotobuf.dto.StudentProto.student parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.study.myprotobuf.dto.StudentProto.student parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.study.myprotobuf.dto.StudentProto.student parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.study.myprotobuf.dto.StudentProto.student parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.study.myprotobuf.dto.StudentProto.student parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.study.myprotobuf.dto.StudentProto.student parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.study.myprotobuf.dto.StudentProto.student prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 定义学生模板
     * </pre>
     *
     * Protobuf type {@code student}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:student)
        com.study.myprotobuf.dto.StudentProto.studentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.study.myprotobuf.dto.StudentProto.internal_static_student_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.study.myprotobuf.dto.StudentProto.internal_static_student_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.study.myprotobuf.dto.StudentProto.student.class, com.study.myprotobuf.dto.StudentProto.student.Builder.class);
      }

      // Construct using com.study.myprotobuf.dto.StudentProto.student.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCourseFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        age_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (courseBuilder_ == null) {
          course_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          courseBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.study.myprotobuf.dto.StudentProto.internal_static_student_descriptor;
      }

      public com.study.myprotobuf.dto.StudentProto.student getDefaultInstanceForType() {
        return com.study.myprotobuf.dto.StudentProto.student.getDefaultInstance();
      }

      public com.study.myprotobuf.dto.StudentProto.student build() {
        com.study.myprotobuf.dto.StudentProto.student result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.study.myprotobuf.dto.StudentProto.student buildPartial() {
        com.study.myprotobuf.dto.StudentProto.student result = new com.study.myprotobuf.dto.StudentProto.student(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.age_ = age_;
        if (courseBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            course_ = java.util.Collections.unmodifiableList(course_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.course_ = course_;
        } else {
          result.course_ = courseBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.study.myprotobuf.dto.StudentProto.student) {
          return mergeFrom((com.study.myprotobuf.dto.StudentProto.student)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.study.myprotobuf.dto.StudentProto.student other) {
        if (other == com.study.myprotobuf.dto.StudentProto.student.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasAge()) {
          setAge(other.getAge());
        }
        if (courseBuilder_ == null) {
          if (!other.course_.isEmpty()) {
            if (course_.isEmpty()) {
              course_ = other.course_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureCourseIsMutable();
              course_.addAll(other.course_);
            }
            onChanged();
          }
        } else {
          if (!other.course_.isEmpty()) {
            if (courseBuilder_.isEmpty()) {
              courseBuilder_.dispose();
              courseBuilder_ = null;
              course_ = other.course_;
              bitField0_ = (bitField0_ & ~0x00000004);
              courseBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCourseFieldBuilder() : null;
            } else {
              courseBuilder_.addAllMessages(other.course_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          return false;
        }
        if (!hasAge()) {
          return false;
        }
        for (int i = 0; i < getCourseCount(); i++) {
          if (!getCourse(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.study.myprotobuf.dto.StudentProto.student parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.study.myprotobuf.dto.StudentProto.student) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <pre>
       * 学生名称
       * </pre>
       *
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       * 学生名称
       * </pre>
       *
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 学生名称
       * </pre>
       *
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 学生名称
       * </pre>
       *
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 学生名称
       * </pre>
       *
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 学生名称
       * </pre>
       *
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <pre>
       * 学生年龄
       * </pre>
       *
       * <code>required int32 age = 2;</code>
       */
      public boolean hasAge() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       * 学生年龄
       * </pre>
       *
       * <code>required int32 age = 2;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <pre>
       * 学生年龄
       * </pre>
       *
       * <code>required int32 age = 2;</code>
       */
      public Builder setAge(int value) {
        bitField0_ |= 0x00000002;
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 学生年龄
       * </pre>
       *
       * <code>required int32 age = 2;</code>
       */
      public Builder clearAge() {
        bitField0_ = (bitField0_ & ~0x00000002);
        age_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.study.myprotobuf.dto.CourseProto.course> course_ =
        java.util.Collections.emptyList();
      private void ensureCourseIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          course_ = new java.util.ArrayList<com.study.myprotobuf.dto.CourseProto.course>(course_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.study.myprotobuf.dto.CourseProto.course, com.study.myprotobuf.dto.CourseProto.course.Builder, com.study.myprotobuf.dto.CourseProto.courseOrBuilder> courseBuilder_;

      /**
       * <pre>
       * 学生所修课程，可能是多门，是一组数组
       * </pre>
       *
       * <code>repeated .course course = 3;</code>
       */
      public java.util.List<com.study.myprotobuf.dto.CourseProto.course> getCourseList() {
        if (courseBuilder_ == null) {
          return java.util.Collections.unmodifiableList(course_);
        } else {
          return courseBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * 学生所修课程，可能是多门，是一组数组
       * </pre>
       *
       * <code>repeated .course course = 3;</code>
       */
      public int getCourseCount() {
        if (courseBuilder_ == null) {
          return course_.size();
        } else {
          return courseBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * 学生所修课程，可能是多门，是一组数组
       * </pre>
       *
       * <code>repeated .course course = 3;</code>
       */
      public com.study.myprotobuf.dto.CourseProto.course getCourse(int index) {
        if (courseBuilder_ == null) {
          return course_.get(index);
        } else {
          return courseBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * 学生所修课程，可能是多门，是一组数组
       * </pre>
       *
       * <code>repeated .course course = 3;</code>
       */
      public Builder setCourse(
          int index, com.study.myprotobuf.dto.CourseProto.course value) {
        if (courseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCourseIsMutable();
          course_.set(index, value);
          onChanged();
        } else {
          courseBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 学生所修课程，可能是多门，是一组数组
       * </pre>
       *
       * <code>repeated .course course = 3;</code>
       */
      public Builder setCourse(
          int index, com.study.myprotobuf.dto.CourseProto.course.Builder builderForValue) {
        if (courseBuilder_ == null) {
          ensureCourseIsMutable();
          course_.set(index, builderForValue.build());
          onChanged();
        } else {
          courseBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 学生所修课程，可能是多门，是一组数组
       * </pre>
       *
       * <code>repeated .course course = 3;</code>
       */
      public Builder addCourse(com.study.myprotobuf.dto.CourseProto.course value) {
        if (courseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCourseIsMutable();
          course_.add(value);
          onChanged();
        } else {
          courseBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * 学生所修课程，可能是多门，是一组数组
       * </pre>
       *
       * <code>repeated .course course = 3;</code>
       */
      public Builder addCourse(
          int index, com.study.myprotobuf.dto.CourseProto.course value) {
        if (courseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCourseIsMutable();
          course_.add(index, value);
          onChanged();
        } else {
          courseBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 学生所修课程，可能是多门，是一组数组
       * </pre>
       *
       * <code>repeated .course course = 3;</code>
       */
      public Builder addCourse(
          com.study.myprotobuf.dto.CourseProto.course.Builder builderForValue) {
        if (courseBuilder_ == null) {
          ensureCourseIsMutable();
          course_.add(builderForValue.build());
          onChanged();
        } else {
          courseBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 学生所修课程，可能是多门，是一组数组
       * </pre>
       *
       * <code>repeated .course course = 3;</code>
       */
      public Builder addCourse(
          int index, com.study.myprotobuf.dto.CourseProto.course.Builder builderForValue) {
        if (courseBuilder_ == null) {
          ensureCourseIsMutable();
          course_.add(index, builderForValue.build());
          onChanged();
        } else {
          courseBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 学生所修课程，可能是多门，是一组数组
       * </pre>
       *
       * <code>repeated .course course = 3;</code>
       */
      public Builder addAllCourse(
          java.lang.Iterable<? extends com.study.myprotobuf.dto.CourseProto.course> values) {
        if (courseBuilder_ == null) {
          ensureCourseIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, course_);
          onChanged();
        } else {
          courseBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * 学生所修课程，可能是多门，是一组数组
       * </pre>
       *
       * <code>repeated .course course = 3;</code>
       */
      public Builder clearCourse() {
        if (courseBuilder_ == null) {
          course_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          courseBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 学生所修课程，可能是多门，是一组数组
       * </pre>
       *
       * <code>repeated .course course = 3;</code>
       */
      public Builder removeCourse(int index) {
        if (courseBuilder_ == null) {
          ensureCourseIsMutable();
          course_.remove(index);
          onChanged();
        } else {
          courseBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * 学生所修课程，可能是多门，是一组数组
       * </pre>
       *
       * <code>repeated .course course = 3;</code>
       */
      public com.study.myprotobuf.dto.CourseProto.course.Builder getCourseBuilder(
          int index) {
        return getCourseFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * 学生所修课程，可能是多门，是一组数组
       * </pre>
       *
       * <code>repeated .course course = 3;</code>
       */
      public com.study.myprotobuf.dto.CourseProto.courseOrBuilder getCourseOrBuilder(
          int index) {
        if (courseBuilder_ == null) {
          return course_.get(index);  } else {
          return courseBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * 学生所修课程，可能是多门，是一组数组
       * </pre>
       *
       * <code>repeated .course course = 3;</code>
       */
      public java.util.List<? extends com.study.myprotobuf.dto.CourseProto.courseOrBuilder> 
           getCourseOrBuilderList() {
        if (courseBuilder_ != null) {
          return courseBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(course_);
        }
      }
      /**
       * <pre>
       * 学生所修课程，可能是多门，是一组数组
       * </pre>
       *
       * <code>repeated .course course = 3;</code>
       */
      public com.study.myprotobuf.dto.CourseProto.course.Builder addCourseBuilder() {
        return getCourseFieldBuilder().addBuilder(
            com.study.myprotobuf.dto.CourseProto.course.getDefaultInstance());
      }
      /**
       * <pre>
       * 学生所修课程，可能是多门，是一组数组
       * </pre>
       *
       * <code>repeated .course course = 3;</code>
       */
      public com.study.myprotobuf.dto.CourseProto.course.Builder addCourseBuilder(
          int index) {
        return getCourseFieldBuilder().addBuilder(
            index, com.study.myprotobuf.dto.CourseProto.course.getDefaultInstance());
      }
      /**
       * <pre>
       * 学生所修课程，可能是多门，是一组数组
       * </pre>
       *
       * <code>repeated .course course = 3;</code>
       */
      public java.util.List<com.study.myprotobuf.dto.CourseProto.course.Builder> 
           getCourseBuilderList() {
        return getCourseFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.study.myprotobuf.dto.CourseProto.course, com.study.myprotobuf.dto.CourseProto.course.Builder, com.study.myprotobuf.dto.CourseProto.courseOrBuilder> 
          getCourseFieldBuilder() {
        if (courseBuilder_ == null) {
          courseBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.study.myprotobuf.dto.CourseProto.course, com.study.myprotobuf.dto.CourseProto.course.Builder, com.study.myprotobuf.dto.CourseProto.courseOrBuilder>(
                  course_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          course_ = null;
        }
        return courseBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:student)
    }

    // @@protoc_insertion_point(class_scope:student)
    private static final com.study.myprotobuf.dto.StudentProto.student DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.study.myprotobuf.dto.StudentProto.student();
    }

    public static com.study.myprotobuf.dto.StudentProto.student getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<student>
        PARSER = new com.google.protobuf.AbstractParser<student>() {
      public student parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new student(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<student> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<student> getParserForType() {
      return PARSER;
    }

    public com.study.myprotobuf.dto.StudentProto.student getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_student_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_student_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rstudent.proto\032\014course.proto\"=\n\007student" +
      "\022\014\n\004name\030\001 \002(\t\022\013\n\003age\030\002 \002(\005\022\027\n\006course\030\003 " +
      "\003(\0132\007.courseB(\n\030com.study.myprotobuf.dto" +
      "B\014StudentProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.study.myprotobuf.dto.CourseProto.getDescriptor(),
        }, assigner);
    internal_static_student_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_student_descriptor,
        new java.lang.String[] { "Name", "Age", "Course", });
    com.study.myprotobuf.dto.CourseProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
